development:
  adapter: mysql2
  encoding: utf8
  database: builder_development
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: builder_production
  username: root
  password:
